const RecipeInfo = [
    {
        id: 1,
        name: "Anchovy Dipping Sauce",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746725752/20170412_210605-768x576_sqqisz.jpg",
        videoId: "Iin6gSFrds0",
        summary: "This flavorful Vietnamese dipping sauce, made with Mắm Nêm (anchovy sauce), combines garlic, chili, lemongrass, lime juice, crushed pineapple, and fish sauce for a bold, sweet-savory-spicy profile. Perfect for pairing with roasted catfish, grilled meats, or Vietnamese salads, it's easily customizable to match your taste preferences.",
        ingredients: [
            "1 Bottle Pagolac Mam Nem 12.5 Fl Oz",
            "2-3 Garlic Cloves (Equals 1 Tablespoon of Minced Garlic)",
            "2-3 Teaspoons Chili Paste (Or Substitute with Fresh Chopped Thai Chilis)",
            "1/2 Tablespoon Sugar",
            "1/2 Tablespoon Fresh Lime Juice",
            "2 Tablespoons Minced Lemongrass (Fresh or Frozen)",
            "1 Can Dole Crushed Pineapples 10 oz",
            "2 Tablespoons Fish Sauce",
        ],
        steps: [
            ["Pour the entire bottle of the Pagolac Mắm Nêm into a bowl.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726085/20170412_211446-768x1189_wlve0b.jpg"],
            ["Add in 1 tablespoon of minced garlic.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726094/20170412_211345-768x631_gkeyju.jpg"],
            ["Add in 2-3 teaspoons of chili paste or if you'd like you can add in some fresh chopped Thai chilis instead.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726103/20170412_211247-768x576_iemoaq.jpg"],
            ["Add in 1/2 tablespoon of sugar and stir to dissolve.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726107/20170412_211017-768x611_v4k06h.jpg"],
            ["Add in 1/2 tablespoon of fresh squeezed lime juice.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726118/20170412_210930-768x647_poepcf.jpg"],
            ["Add in 2 tablespoons of minced lemongrass ( fresh or frozen ).", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726125/20170412_210827-768x643_g0qx3s.jpg"],
            ["Pour in the the Dole Crushed Pineapples including the juice and stir. If you are using a 20 oz can of Dole Crushed Pineapples, just pour in half of the crushed pineapples and half of the juice in the can. Save the rest for some other use.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726135/20170412_210731-768x668_zfluhh.jpg"],
            ["Lastly add in 2 tablespoons of fish sauce and stir.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726139/20170412_210517-768x630_jwhsax.jpg"],
            ["Taste and adjust the dipping sauce to suit your taste. Add more fish sauce if you would like it saltier and add more sugar if you would like it sweeter. If you find it to be too salty then add more water or lemon juice.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746725752/20170412_210605-768x576_sqqisz.jpg"],
            ["This dipping sauce is usually served with the Vietnamese Roasted Catfish and also the  Grilled Beef with Squid and Shrimp as seen below. But some Vietnamese salads with also use this dipping sauce as well except the crushed pineapples would usually be omitted from the recipe.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746726499/IMG_20170412_215145_298-595x595_lxvfnh.jpg"],
        ]        
    },
    {
        id: 2,
        name: "Artichoke And Pork Rib Soup",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746727092/20180303_201536-768x621_r5psph.jpg",
        videoId: "",
        summary: "Artichoke and Pork Rib Soup is a delicious and hearty dish that blends the rich flavors of tender pork riblets and artichokes in a savory broth. With the addition of aromatic seasonings and fresh garnishes, this comforting soup offers a perfect balance of flavors and textures.",
        ingredients: [
            "4 Fresh Artichokes (Medium Size) (Or You Can Use 2 Jumbo Sized Artichokes)",
            "2 Pounds Pork Riblets",
            "12 Cups Water",
            "1/2 Tablespoon + 1 Teaspoon Salt",
            "3 1/2 Tablespoons Totole Chicken Soup Base Mix",
            "2 Teaspoons Sugar",
            "For garnish",
            "Chopped Green Onions",
            "Chopped Cilantro",
            "Black Pepper",
            "For dipping sauce:",
            "Maggi Seasoning",
            "Red Thai Chili",
        ],
        steps: [
            ["Parboil the pork riblets for 10 minutes. Place the pork riblets in a pot and fill with water. Boil for 10 minutes. Then drain and wash the pork riblets.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746727099/arti-1_m4s2sl.jpg"],
            ["Wash the artichokes and remove the stems.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746727105/20180302_190454-768x576_yyqtvy.jpg"],
            ["Fill a stock pot or large wok with 12 cups of water. Add in the salt, the Totole Chicken Soup Base Mix, the sugar, the artichokes, and the pork riblet to the pot. Bring to a boil. Skim off any foam during the cooking process. Reduce the heat to low. Cover and simmer for 1 hour.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746727111/20180303_164720-768x576_c6brqt.jpg"],
            ["Taste and adjust the soup if necessary. If it is a bit salty, simply add more water.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746727118/arti-3_ytvums.jpg"],
            ["Transfer the soup to a bowl. Garnish with some chopped cilantro and green onions. Sprinkle on some black pepper.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746727092/20180303_201536-768x621_r5psph.jpg"],
            ["Serve with white rice with a soy sauce dip for the meat. Pour some Maggi Seasoning in a small dipping bowl and add one chopped Thai chili.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746727167/arti-2_pmudix.jpg"],
            ["I would recommend using JUMBO artichokes if available as they have more meat at the bottom of the base of the artichoke petals. If jumbo artichokes are not available then you can use medium sized artichokes.", ""],
            ["Taste and adjust the soup. If it needs more flavor, add more of the Totole Chicken Soup Base Mix. Add more salt if needed. If it is too salty, add more water.", ""],
            ["The tender base of the petals and the artichoke heart is edible. Just scrape off the tender part with your teeth. ", ""],
        ]        
    },
    {
        id: 3,
        name: "Asian Fruit Cocktail",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746729020/Capture-che-400x400_nrpwju.png",
        videoId: "KjvDrGduwB4",
        summary: "A refreshing and colorful Vietnamese dessert, Chè Thái blends tropical canned fruits, chewy jelly, and creamy half & half into a sweet, chilled treat. Popular at gatherings and on hot days, this fruit cocktail delivers a delightful mix of textures and flavors in every spoonful.",
        ingredients: [
            "1 Can Lychee In Syrup",
            "1 Can Jackfruit In Syrup",
            "1 Can Longan In Syrup",
            "1 Can Green Ai-Yu Jelly (Add 2 cans if you want your Che Thai to have a green tint)",
            "1 Can Toddy Palm's Seed",
            "1 Container Half & Half (64 fl oz)",
            "For The Faux Pomegranates (Optional)",
            "1 Can Water Chestnuts In Water",
            "Red Food Coloring"
        ],
        steps: [
          ["Steps 2 through 12 is to make the faux pomegranites. Skip these  steps if you do not want to add them to your Che Thai. This desert is best served the same day but will keep in the fridge until the day after. Please finish by the end of the next day otherwise the jackfruit will begin to soften.", ""],
          ["Drain the chestnuts.", ""],
          ["Cut the water chestnuts into cubes.", ""],
          ["Add a few drops of food coloring and mix.", ""],
          ["Add enough tapioca starch to completely coat the water chestnuts.", ""],
          ["Pour the water chestnuts into a colander to shake off any excess flour.", ""],
          ["Add water to a pot and turn the heat to high.", ""],
          ["Bring a pot of water to boil and add int the water chestnuts.", ""],
          ["Once the water chestnuts have been added bring the pot of water back to a boil.", ""],
          ["Then lower the heat slightly and cook the water chestnuts for about 3 minutes.", ""],
          ["Remove from the pot and strain.", ""],
          ["Set it aside to cool.", ""],
          ["Pour the syrups from the Lychee and Jackfruit into an ice bucket or some sort of large container. Then cut the Lychees in half and add to the ice bucket. Cut the Jackfruit into strips and add to the ice bucket.", ""],
          ["Pour the Longan (leave as whole) along with its syrup into the ice bucket.", ""],
          ["Pour the liquid from the can of green jelly into the ice bucket. Cut the green jelly into cubes and add to the ice bucket. If you would like for your Che Thai to have a green tint then add an extra can of green jelly along with its liquid into the ice bucket.", ""],
          ["Drain and rinse the Toddy Palm's Seed. Cut in half and add to the ice bucket.", ""],
          ["Add the faux pomegranites to the ice bucket.", ""],
          ["Fill the ice bucket to the top with Half & Half.", ""],
          ["Gently stir to combine.", ""],
          ["Place in the fridge for about an hour before serving.", ""],
          ["Then serve over crushed ice.", ""],
        ],
    },
    {
        id: 4,
        name: "Asian Grilled Shrimp",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746740489/20200627_224326-480x640_tvx9do.jpg",
        videoId: "",
        summary: "Asian Grilled Shrimp is a flavorful and aromatic dish featuring extra jumbo prawns marinated in a savory mix of garlic, spices, and fish sauce. Grilled in rich butter for added depth, it's served with your choice of a tangy lemon dip or a creamy sriracha mayo, making it a perfect centerpiece for any seafood lover’s meal.",
        ingredients: [
            "2 Pounds Extra Jumbo Prawns With Head and Skin On",
            "1 Tablespoon Totole Granulated Chicken Flavor Soup Base Mix",
            "1/2 Teaspoon Crushed Chili Flakes",
            "1/2 Teaspoon Garlic Powder",
            "1/4 Teaspoon Chinese Five Spice Powder",
            "1/8 Teaspoon Black Pepper",
            "1 Tablespoon Fish Sauce",
            "5 Garlic Cloves (Minced)",
            "4 Tablespoons Of Butter (Divided)",
            "Lemon Juice Dip (2 Yellow Lemons, Salt and Black Pepper)",
            "Mayo Sriracha Dip (Kewpie Japanese Mayo and Sriracha Hot Sauce)",
            "Equipment: 12'' Cast Iron Skillet Or A Cast Iron Stove Top Grill"
          ],
        steps: [
          ["Trim the prawns. Cut and remove the long antennas as well as the sharp spines above the prawn's head. Turn the prawns over and cut off all of the legs.", ""],
          ["Wash the prawns in cold water with a tablespoon of salt. Rinse to remove the salt.", ""],
          ["Dump all 2 pounds of the prawns into a large mixing bowl and add in the marinade ingredients. Add in 1 tablespoon of the Totole Granulated Chicken Powder, 1/2 teaspoon of the crushed chili flakes, 1/2 teaspoon of garlic powder, 1/4 teaspoon of the Chinese Five Spice powder, 1/8 teaspoon of black pepper, 1 tablespoon of fish sauce and the minced garlic cloves. Toss to combine everything. Marinate for 15 minutes.", ""],
          ["The prawns will need to be cooked in 2 batches so divide the prawns evenly in half. Let's cook the first batch ! Heat the cast iron skillet on medium-high and once the pan is hot add in 2 tablespoons of butter. Allow the butter to melt then lay the prawns down into the pan in a single layer. Don't forget to scoop some of the minced garlic from the bottom of the mixing bowl and add it to the pan. Cook the prawns until they are pink on one side.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746740687/1_j0cxtq.jpg"],
          ["Then turn the prawns over and cook the prawns until they are lightly browned. The prawns are done once the tail has curled up. Cook approximately 2 minutes on the first side and 1 minute on the other side or until lightly browned.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746740693/2_d4mkwp.jpg"],
          ["Repeat the process with the second batch of prawns.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746740698/3_bax7pw.jpg"],
          ["There are 2 different dips to choose from: To make a lemon juice dip, squeeze a lemon wedge or two into a small dipping bowl. Then add a pinch of salt and black peper. Mix to combine. To make a mayo siracha dip, squeeze some japanese mayo into a small dipping bowl then squeeze in some siracha hot sauce. Mix to combine. I personally prefer the mayo siracha dip but either will work.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746740702/4_l1uvzf.jpg"],
          ["How to eat this: Break off the head of the prawns . Suck the juices from the opening of the heads ( optional ). Lick the the seasoning off of the prawns then peel them. Dip the prawns into your choice of dipping sauce.", ""],
        ],
    },
    {
        id: 5,
        name: "Asparagus Crab Soup",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1740795793/20210403_154041_resized-768x576_ue3f0h.jpg",
        videoId: "qpXFMMOY1Vs",
        summary: "Vietnamese Asparagus Crab Soup (Súp Măng Tây Cua) is a light, elegant soup that combines the delicate sweetness of crab meat with tender asparagus in a silky, flavorful broth. This classic Vietnamese dish is often served as an appetizer at special gatherings, offering a perfect balance of savory and umami flavors.",
        ingredients: [
            "2 (32 oz) Cardboard Containers of Organic Chicken Broth",
            "1 (12 oz) Container of Lump Crab Meat (Equals 2 Cups of Lump Crab Meat)",
            "1 (28 1/2oz) Can Whole Peeled Asparagus (Drained and Cut lengthwise)",
            "2 (15 oz) Cans Quail Eggs In Water (Drained)",
            "2 Large Eggs At Room Temperature (Beaten)",
            "3 Tablespoons Totole Granulated Chicken Flavor Soup Base Mix",
            "1/2 Teaspoon White Pepper",
            "1 Teaspoon Sesame Oil",
            "1/2 Tablespoon Fish Sauce",
            "2 Teaspoons Shao Hsing Rice Cooking Wine",
            "1/3 Cup Tapioca Starch",
            "1 Cup Cold Water",
            "Chopped Cilantro",
            "Chopped Green Onions",
            "Lee Fried Red Onion (Optional)",
        ] ,
        steps: [
            ["In a large soup pot add the chicken broth and bring it to a boil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216227/20170517_200644-768x681_cjnfv1.jpg"],
            ["Open the can of crab meat and slightly separate the meat with your hands.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216260/20170517_1355010-768x576_p2frnp.jpg"],
            ["Drain and rinse Asparagus Spears. Then cut into smaller pieces and set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216266/20170517_200419-768x481_lkbect.jpg"],
            ["Drain and rinse Quail Eggs. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216281/20170517_200325-768x617_pihyan.jpg"],
            ["Crack and beat the eggs. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216286/20170517_195841-768x666_lulqag.jpg"],
            ["Make the tapioca starch mixture. Pour cold water into a bowl. Then gradually stir in the tapioca starch. Do not add in all the tapioca starch at once as it will become one big clump making it difficult to stir the mixture. Stir until all the tapioca starch has dissolved. Then set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216298/20170517_200150-768x661_n4szcz.jpg"],
            ["Place all items on the counter next to the soup pot.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216304/20170517_181353-768x498_piwibi.jpg"],
            ["Once the chicken broth is warm add in all the seasonings: Totole granulated chicken flavor soup base mix, white pepper, sesame oil, and fish sauce.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216309/20170517_200050-768x550_pdpgn4.jpg"],
            ["Once the soup has come to a boil add the crab meat, asparagus spears, and the quail eggs. Stir to combine everything.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216318/20170517_195741-768x640_c5gflm.jpg"],
            ["Then reduce the heat to LOW.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216328/20170517_195610-768x559_vfqw0r.jpg"],
            ["Time to add the Tapioca Starch mixture. Give it a quick stir then slowly add it into the soup. Only add in one ladle of the Tapioca Starch at a time until it reaches the desired consistency. Stir the soup and wait about a minute to add more of the Tapioca Starch to give the soup some time to thicken. Stir the Tapioca Starch once again before adding more of it into the soup. Add the 2nd ladle of the Tapioca Starch mixture and stir. Then pour in the rest of the mixture into the soup and stir. If the soup is not as thick as you'd like, make more of the tapioca starch mixture and add it to the soup until it reaches the desired thickness.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216334/20170517_195442-768x566_pttdpd.jpg"],
            ["Now turn the heat to high and continue to slowly stir the soup until it comes to a bubble.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216343/20170517_194946-768x548_jmiu9k.jpg"],
            ["Once it has come to a bubble gradually add in the beaten egg while stirring in a circular motion. This will create the nice egg ribbons.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216348/20170517_181619-768x607_mf6oih.jpg"],
            ["Once all of the beaten eggs have been added turn off the heat, sprinkle on some white pepper or black pepper. Garnish with the chopped cilantro and chopped green onions. You can also top with some of the Lee's Fried Onions (Optional).", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1743216354/20210403_154508_resized-768x576_kqkgsl.jpg"],
            ["Serve immediately while hot otherwise the soup has a tendency to thin out as it cools.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1740795793/20210403_154041_resized-768x576_ue3f0h.jpg"]
        ]
        
    },
    {
        id: 6,
        name: "Baby Bok Choy Soup",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745109930/20161205_194949-400x400_u6knon.jpg",
        videoId: "",
        summary: "A comforting Vietnamese soup that balances savory ground pork, fragrant ginger, and tender baby bok choy in a clear, flavorful broth. This dish features marinated pork simmered in a seasoned stock, finished with lightly cooked bok choy to preserve its crunch. Traditionally served with white rice, it's a wholesome, everyday favorite in Vietnamese home cooking.",
        ingredients: [
        "1/2 Pound Ground Pork",
        "1/2 Tablespoon Fish Sauce",
        "1/4 Teaspoon Garlic Salt",
        "1/8 Teaspoon Black Pepper",
        "1/2 Teaspoon Totole Chicken Soup Base Mix",
        "1 Tablespoon Chopped Shallots",
        "10 Cups Water",
        "1/2 Tablespoon Salt",
        "1 1/2 Tablespoons Totole Chicken Soup Base Mix",
        "1/2 Cup Sliced Ginger",
        "1 Package Baby Bok Choy"
        ],
        steps: [
          ["In a bowl combine the ground pork with the fish sauce, garlic salt, black pepper, Totole Chicken Soup Base Mix, and chopped shallots. Marinate for 30 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110243/20161205_201244-768x743_kshbtu.jpg"],
          ["Then separate into smaller pieces.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110249/20161205_200841-768x576_krbz1x.jpg"],
          ["Wash the Baby Bok Choy 2 to 3 times.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110322/20161205_194949-768x576_k4kng5.jpg"],
          ["Cut into smaller bite size pieces. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110260/20161205_200430-768x645_q7sxnt.jpg"],
          ["Peel and slice the ginger.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110266/20161205_200714-768x711_jhbkfn.jpg"],
          ["Fill a pot with 10 cups of water. Add in the salt, Totole Chicken Soup Base Mix and ginger. Bring to a boil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110271/20161205_200314-768x590_fldwqo.jpg"],
          ["Add in the marinated pork.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110277/20161205_200125-768x699_aw1s22.jpg"],
          ["And bring the soup back to a boil", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110282/20161205_195937-768x621_k8cla5.jpg"],
          ["Remove any scum from the top of the soup.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110302/20170504_174423-768x651_h5azfj.jpg"],
          ["Add in the bok choy and once again bring the soup back to a boil for the last time.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110308/20161205_195817-768x424_lopx87.jpg"],
          ["Reduce the heat to Medium and cook for about 1 to 2 minutes until the bok choy stems are slightly tender. Do not cook them for too long as they will become too soft. Then turn off the heat.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110314/20161205_195432-768x637_iuhyuw.jpg"],
          ["Sprinkle on some black pepper.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110322/20161205_194949-768x576_k4kng5.jpg"],
          ["Serve with white rice.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1745110332/20170504_160548-768x576_a7vf5k.jpg"],
        ],
    },
    {
        id: 7,
        name: "Banana Ice Cream Pops",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746749152/Capture-banana2-400x400_vvjudz.png",
        videoId: "f29OgJpkbIw",
        summary: "Vietnamese Banana Ice Cream Pops (Kem Chuối) are a nostalgic frozen treat made with sweet Manzano bananas, rich coconut milk, shredded coconut, and crunchy roasted peanuts. Layered and frozen on sticks, they offer a creamy, nutty, and naturally sweet flavor that's both refreshing and satisfying on hot days.",
        ingredients: [
            "1 Bunch Manzano Bananas",
            "1 Package Frozen Shredded Coconuts (7 oz)",
            "1 Cup Crushed Roasted Peanuts",
            "12 Popsicle Sticks",
            "Saran Wrap",
            "1 Can Coconut Milk (14 oz)",
            "Pinch of Salt",
            "3 Tablespoons Sugar",
            "3 Tablespoons Tapioca Starch",
            "6 Tablespoons Cold Water",
          ],          
        steps: [
          ["In a bowl mix the tapioca starch with the cold water. Stir to dissolve the tapioca starch and set aside.", ""],
          ["In a saucepan on Medium Low heat add in the coconut milk, salt and sugar. Stir to dissolve the sugar.", ""],
          ["Then gradually pour in the tapioca starch mixture and stir.", ""],
          ["Once all of the tapioca starch mixture has been poured into the pan turn the heat up to Medium High. Continue to stir until it has thickened. Then remove from heat.", ""],
          ["Place a banana on a sheet of saran wrap and slightly flatten it.", ""],
          ["Spread on the thickened coconut milk.", ""],
          ["Next sprinkle on a handful of the shredded coconuts.", ""],
          ["Add the crushed peanuts.", ""],
          ["Then flip the banana over and repeat the process.", ""],
          ["Wrap the banana in saran wrap and freeze for 4 hours.", ""],
        ],
    },
    {
        id: 8,
        name: "Bánh Mì - Vietnamese Sandwich",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828057/20161208_152046-400x400_puhvkt.jpg",
        videoId: "",
        summary: "This classic Bánh Mì brings together crisp baguette, rich pâté, savory Vietnamese cold cuts, and tangy pickled veggies. Topped with jalapeños and fresh cilantro, it's a bold, flavorful sandwich with a perfect balance of textures and tastes.",
        ingredients: [
            "Fresh Baked Baguette",
            "Pork Liver Pâté",
            "Vietnamese Mayonnaise",
            "Soy Sauce",
            "Sliced Giò Thủ (Head Cheese)",
            "Sliced Jambon (Cooked, Cured, Formed Pork Wrapped in Pork Skin)",
            "Sliced Giò Lụa (Vietnamese Cooked Pork Roll)",
            "Pickled Daikons & Carrots",
            "Sliced Jalapeños",
            "Cilantro"
        ],          
        steps: [
          ["Slice the baguette lengthwise but not completely through. Lightly toast the baguette. Then spread on some Pork Liver Pate and Vietnamese Mayonaise on the bottom half of the baguette and drizzle some soy sauce on the upper half.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828154/20161208_081950-768x576_dwruhg.jpg"],
          ["Place a slice of the Gio Thu ( Head Cheese ) on the bottom half of the baguette.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828238/20161208_082033-768x576_ooi8tf.jpg"],
          ["Then add a slice of Jambon ( Cooked Cured Formed Pork Wrapped in Pork Skin ).", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828245/20161208_082109-768x576_pwrmvs.jpg"],
          ["And also add a slice of Gio Lua ( Vietnamese Cooked Pork Roll ).", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828253/20161208_082141-768x576_dkrzlw.jpg"],
          ["Next add on the Pickled Daikons & Carrots.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828261/20161208_082239-768x576_nirglb.jpg"],
          ["Add a few slices of jalapenos.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828266/20161208_082324-768x576_atjnpz.jpg"],
          ["And lastly add a sprig or two of cilantro.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828274/20161208_082349-768x576_xkfoms.jpg"],
          ["And voila! You've got yourself a Banh Mi to enjoy!", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828278/20161208_081806-1-768x576_pctxio.jpg"],
        ],
    },
    {
        id: 9,
        name: "Vietnamese Beef Stew - Bò Kho",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828621/20171030_174703-768x722_zee2lx.jpg",
        videoId: "UUNec_kdJso",
        summary: "A rich and hearty Vietnamese beef stew, Bò Kho is made with tender beef, aromatic herbs, and spices. The dish is known for its savory, slightly spicy flavor, with a deliciously rich broth. It's traditionally served with pho noodles or French baguettes.",
        ingredients: [
            "2 1/2 Pounds Boneless Beef Chuck Or Brisket (cut into bite-size pieces)",
            "1 Package Bò Kho Powder (2 oz)",
            "30 Cups Water",
            "2 Large Carrots (peeled and sliced)",
            "7 Roma Tomatoes (cut into wedges)",
            "For marinating the beef:",
            "1 Tablespoon Sugar",
            "1 Teaspoon Salt",
            "1 Tablespoon Bò Kho Powder",
            "2 Tablespoons Fish Sauce",
            "1/8 Teaspoon Black Pepper",
            "1/2 Tablespoon Annatto Seed Oil",
            "To make the Annatto Seed Oil:",
            "2 Tablespoons Vegetable Oil",
            "1 Tablespoon Annatto Seeds",
            "For sautéing tomatoes:",
            "2 Tablespoons Vegetable Oil",
            "1 Tablespoon Sugar",
            "1/2 Teaspoon Salt",
            "For cooking beef:",
            "2 Tablespoons Vegetable Oil",
            "3 Stalks Lemongrass (flattened, cut into 2\" pieces)",
            "1 Knob Ginger (approx. 2\"x1/2\", sliced)",
            "5 Garlic Cloves",
            "1 Cinnamon Stick",
            "4 Star Anise",
            "5 Bay Leaves",
            "Season the stew with:",
            "1 Tablespoon Salt",
            "1 Tablespoon Sugar",
            "1/2 Cup Fish Sauce",
            "3 Tablespoons Totole Chicken Soup Base Mix",
            "Remaining Bò Kho Powder",
            "Remaining Annatto Seed Oil",
            "1 Can Tomato Paste (6 oz)",
            "Garnish with:",
            "Bean Sprouts (only if eating with pho noodles; otherwise omit if serving with french bread)",
            "Thinly Sliced Yellow Onions",
            "Chopped Green Onions",
            "Chopped Cilantro",
            "Thai Basil",
            "Chopped Thai Chilis",
            "Sprinkle of Black Pepper",
            "For dip:",
            "Lemon Wedges",
            "Salt",
            "Black Pepper",
            "For serving with dish:",
            "Pho Noodles or French Baguettes"
        ],          
        steps: [
          ["Make the Annatto Seed Oil. In a small pan over medium heat add in 2 tablespoons of vegetable oil. Add in the Annatto Seeds and stir the annatto seeds around the pan until the seeds have bled. It should only take about a minute. Do not cook the seeds for too long as it will burn and will turn bitter.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830421/20171030_105825-768x673_l8qey0.jpg"],
          ["Strain into a bowl. Discard the seeds and reserve the oil. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830426/20171030_105929-768x815_j7tsdv.jpg"],
          ["Cut the beef into bite size pieces. Marinate the beef with 1 tablespoon of sugar, 1 teaspoon salt, 1 tablespoon bo kho powder, 1/8 teaspoon black pepper, 2 tablespoons fish sauce and 1/2 tablespoon annatto seed oil. Cover and refrigerate overnight or minimum one to two hours.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830431/20171030_110305-768x658_azbtmp.jpg"],
          ["Saute the tomatoes. In a pan over medium heat add in 2 tablespoons of vegetable oil. Toss in the tomatoe wedges and add in 1 tablespoon of sugar and 1/2 teaspoon of salt.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830437/20171030_115138-768x576_ztse7f.jpg"],
          ["Cook the tomatoes for about 5 minutes or until they are slightly soft. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830443/20171030_1157050-768x576_thhtxk.jpg"],
          ["Cook the beef. In a wok on medium-high heat add 2 tablespoons of vegetable oil. Once the pan is warm add in ginger, garlic and lemongrass. Saute for 1 minute.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830448/20171030_120219-768x576_rptjjf.jpg"],
          ["Toss in the cinnamon stick, star anise and bay leaves. Saute for 1 minute.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830454/20171030_120241-768x576_v5h3mw.jpg"],
          ["Add the beef to the wok.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830459/20171030_120329-768x616_rdj2y7.jpg"],
          ["Saute the beef for about 5 minutes or until browned. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830465/20171030_121047-768x576_sydna3.jpg"],
          ["Pour 30 cups of water into a large soup pot. Add in 1 tablespoon of salt, 1 tablespoon sugar, 1/2 cup of fish sauce, 3 tablespoons of the Totole Chicken Soup Base Mix. Bring to a boil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830470/20171030_120727-768x561_ilzqkk.jpg"],
          ["Then add in the cooked beef.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830476/20171030_121248-768x623_pywqad.jpg"],
          ["Also add in the slightly cooked tomatoes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830481/20171030_121443-768x642_cfbhq1.jpg"],
          ["Add in the remaining bo kho powder.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830488/20171030_121524-768x549_t2gnpw.jpg"],
          ["Add in the remaining Annattto Seed Oil", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830492/20171030_122900-768x613_xi6mke.jpg"],
          ["And lastly add in the entire can of tomato paste.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830499/20171030_164816-768x671_jlefvc.jpg"],
          ["Bring the stew back to a boil and remove any scum from the top of the soup.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830503/20171030_122247-768x578_rg4qtu.jpg"],
          ["Cover and reduce the heat. Simmer for 2 hours and 15 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830508/20171030_122637-768x506_ile5dq.jpg"],
          ["Then add in the carrots and bring the stew back to a boil. Reduce the heat, cover and continue to simmer for another 45 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830515/20171030_150203-768x585_gr4bfx.jpg"],
          ["Turn off the heat once the meat is tender. Before serving be sure to fish out the cinnamon stick, lemongrass stalks, star anise pods, and bay leaves.", ""],
          ["Ladle the beef stew over some cooked pho noodles or serve with french baguettes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830524/20171030_175050-768x618_cgfwsp.jpg"],
          ["Garnish with some thinly sliced yellow onions, chopped green onions, chopped cilantro, fresh thai basils, a sprinkle of black pepper and some chopped Thai chilis ( optional ).", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830531/20171030_1711250-768x576_gqybnh.jpg"],
          ["Add beansprouts only if you are eating the beef stew with the pho noodles. Omit the beansprouts if serving with french baguettes. Also serve with some lime wedges on the side.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830535/20171030_165324-768x574_u6srpq.jpg"],
          ["Make a dip for the beef. Squeeze a wedge or two of lime into a small bowl. Then add a pinch of salt and black pepper. Stir to combine.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746830544/20171030_163705-768x550_iie8do.jpg"],
          ["Enjoy your bowl of Bo Kho!", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746828621/20171030_174703-768x722_zee2lx.jpg"],
        ],
        
    },
    {
        id: 10,
        name: "Stuffed Bitter Melon Soup - Canh Khổ Qua Nhồi Thịt",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746836176/SPhotoEditor-20190116_173254-768x576_egcwx6.jpg",
        videoId: "",
        summary: "",
        ingredients: [
        "1 Pound Pork Neck Bones",
        "4 Bitter Melons ( Each about 8''- 9'' long or a little bit longer than the width of your hand stretched out - Cut evenly into 4 pieces )",
        "For mixing with the ground pork",
        "1 Pound Ground Pork ( Do not buy the lean ground pork )",
        "1/4 Teaspoon Salt",
        "1/8 Teaspoon sugar",
        "1/2 Teaspoon Totole Chicken Flavor Soup Base Mix",
        "1 Teaspoon Fish Sauce",
        "1/8 Teaspoon Black Pepper",
        "1 Tablespoon Chopped Shallots",
        "1 Tablespoon Chopped Green Onions ( Bottom white part only )",
        "3 Tablespoons Cooked Chopped Wood Ear Mushrooms ( Soak in hot water for 10 minutes then chop )",
        "1/4 Cup Plus 2 Tablespoons Cooked Chopped Glass or Mung Bean Noodles ( Soak in hot water for 10 minutes then chop )",
        "For the broth:",
        "12 Cups water",
        "1 Teaspoon Salt",
        "3 Tablespoons Totole Chicken Flavor Base Mix",
        "1 Teaspoon sugar",
        "For garnishing:",
        "Chopped Cilantro",
        "Chopped Green Onions",
        "For dipping sauce:",
        "Fish Sauce",
        "Chopped Red Thai Chili",
        ],
        steps: [
          ["Parboil the bones. Place the bones in a pot with enough water to cover. Bring the water to a boil. Then slightly reduce the heat to prevent over boiling and boil the bones for 5 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746836943/20190116_202846-768x576_sdgtpy.jpg"],
          ["Remove the bones from the pot and rinse under cold water. Drain and set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746836948/20190116_202357-768x576_vxa3st.jpg"],
          ["Soak the mung bean (vermicelli) glass noodles and the wood ear fungus mushrooms in hot water for 10 minutes. Drain and quickly rinse under cold water. Then rough chop and set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746836956/IMG_2019-01-17_00-14-41-768x768_qp8slb.jpg"],
          ["In a large bowl mix together the ground pork with the salt, sugar, totole chicken flavor base mix, fish sauce, black pepper, shallots , bottom part of the green onions, chopped wood ear mushrooms and the chopped noodles", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746836962/20190116_202115-768x576_xdk8gq.jpg"],
          ["Cut the bitter melons into quarters. Remove and discard the end caps.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746836967/20190116_202559-768x576_kvh0ra.jpg"],
          ["Use a knife to remove the inner parts of the melons. Then use your thumb to push it out or use your knife to twist it out.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746837012/IMG_2019-01-16_20-20-38-768x768_y74okv.jpg"],
          ["Stuff the melons with the meat mixture.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746837019/20190116_144804-768x576_aisexx.jpg"],
          ["In a large pot pour in the 12 cups of water. Add in the salt, the totole chicken flavor soup base mix and sugar. Bring to a boil. Then add in the pork neck bones and bring back to a boil. Reduce the heat to simmer, cover the pot with a lid and simmer for 20 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746837026/20190116_201705-768x576_sxqwqu.jpg"],
          ["Then add the stuffed melons to the pot and bring to a boil. Cover the pot with a lid and reduce the heat to simmer for another 20 to 25 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746837034/20190116_201409-768x576_pqi1xq.jpg"],
          ["The soup can be served with or without the pork neck bones.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746837041/20190116_200847-768x576_i8vcdd.jpg"],
          ["Garnish with some chopped cilantro and chopped green onions. Sprinkle on some black pepper.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746836176/SPhotoEditor-20190116_173254-768x576_egcwx6.jpg"],
          ["Serve with white rice and a dipping sauce. Fill a small dipping bowl with some fish sauce and add some chopped thai chili.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746837077/IMG_2019-01-16_17-24-25-768x768_jocxaj.jpg"],
        ],
    },
    {
        id: 11,
        name: "Braised Bacon",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841444/20161120_170245-768x701_tj5zpx.jpg",
        videoId: "AzGotQ0GqPc",
        summary: "Braised Bacon is a savory-sweet comfort dish that combines caramelized sugar, smoky bacon, and tender carrots simmered in a rich fish sauce broth. This dish is full of bold flavors and is best enjoyed with fluffy white rice, crisp cucumber slices, and a spicy Thai chili pepper on the side.",
        ingredients: [
            "For the caramel:",
            "2 tablespoons sugar",
            "For adding to the pot:",
            "1 package of bacon (cut into smaller pieces)",
            "3 garlic cloves (minced)",
            "1 tablespoon fish sauce",
            "1 tablespoon sugar",
            "1 large carrot (peeled and thinly sliced, about 1 cup)",
            "2 cups hot water",
            "For garnishing:",
            "A handful of chopped green onions",
            "Sprinkle of black pepper",
            "For serving with:",
            "White rice",
            "Sliced Japanese cucumbers",
            "A Thai chili pepper"
        ],
        steps: [
          ["Fill a kettle with 2 cups of water and bring it to a boil.", ""],
          ["Cut the bacon into smaller pieces.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841659/20161120_183841-768x466_q3njam.jpg"],
          ["Peel and thinly slice the carrot.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841669/20161120_152921-768x576_zz9zbh.jpg"],
          ["Mince the garlic cloves.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841676/20161120_153005-768x576_ydcj5z.jpg"],
          ["Chop the green onions.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841688/20161120_155109-768x576_cgpl2s.jpg"],
          ["Slice the Japanese Cucumbers.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841695/20161120_181913-768x697_xa6slg.jpg"],
          ["Carmelize the sugar. In a pot on Medium heat melt 2 tablespoons of sugar. Once the sugar starts to melt swirl it around the pan. During this entire process do not use a spoon or any utensil to stir the sugar. Only pick up the pan and swirl the melted sugar until it has all dissolved.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841703/20161120_183654-768x604_v59rnq.jpg"],
          ["Once the melted sugar has reached an amber color and begins to smoke add in the bacon. Be very careful as the carmelized sugar can quickly burn within seconds. Then stir the bacon for 1 minute.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841708/20161120_183606-768x666_o1n3l7.jpg"],
          ["Then add in the minced garlic and stir for 1 minute.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841714/20161120_183412-768x674_bd3q75.jpg"],
          ["Add in 1 tablespoon of fish sauce.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841721/20161120_183250-768x530_xmgl9s.jpg"],
          ["Also add in the carrots and cook for 5 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841728/20161120_183202-768x678_wzughk.jpg"],
          ["Then pour in the hot water from the tea kettle.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841734/20161120_182924-768x517_datufg.jpg"],
          ["And 1 tablespoon sugar.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841743/20161120_182550-768x592_ve9u5j.jpg"],
          ["Bring to a boil. Then reduce the heat to Medium-Low and simmer for 15 minutes. Stirring occasionally.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841751/20161120_182810-768x710_apadk8.jpg"],
          ["Cook until the carrots are as tender as you like them then turn off the heat.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841759/20161120_182323-768x711_vi7lve.jpg"],
          ["Garnish with chopped green onion. Sprinkle on some black pepper.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841762/20161120_182054-768x576_yccq4e.jpg"],
          ["Serve with white rice, sliced japanese cucumbers and a thai chili pepper.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746841444/20161120_170245-768x701_tj5zpx.jpg"],
        ],
    },
    {
        id: 12,
        name: "Carmelized Fish",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842189/20161107_210457-1-768x723_xj9dwh.jpg",
        videoId: "",
        summary: "Carmelized Fish (Cá Kho) is a traditional Vietnamese comfort dish that brings rich, savory flavors together in a sweet and salty caramelized sauce. Made with tender catfish steaks marinated in garlic, shallots, and fish sauce, then simmered in young coconut juice with mushrooms and Thai chilies, this dish is bold yet balanced. Serve it over fluffy white rice with crisp cucumbers or tangy pickled beansprouts.",
        ingredients: [
            "For washing the fish:",
            "6 catfish steaks",
            "Cold water",
            "1 tablespoon salt",
            "For the marinade:",
            "2 1/2 tablespoons fish sauce",
            "1 teaspoon Vietnamese caramel sauce (also called thick soy sauce or nước màu)",
            "1/2 teaspoon garlic salt",
            "1/8 teaspoon black pepper",
            "3 garlic cloves (equals 1 tablespoon minced garlic)",
            "1 shallot (equals 2 tablespoons chopped shallots)",
            "For adding to the pan:",
            "1 tablespoon vegetable oil",
            "1 can peeled straw mushrooms",
            "1 can young coconut juice (15 oz)",
            "3 tablespoons fish sauce",
            "1 tablespoon sugar",
            "1/4 teaspoon garlic salt",
            "2 Thai chili peppers",
            "For garnishing:",
            "Sprinkle of black pepper",
            "Chopped green onions",
            "For serving with:",
            "White rice",
            "Sliced Japanese cucumbers or Vietnamese pickled beansprouts (recipe available on my website)"
        ],          
        steps: [
          ["Place the fish steaks in a large bowl and fill it with some cold water. Pour in a tablespoon of salt. Wash the fish steaks with the salted water. Then rinse a few times to remove the salt and pat dry.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842071/20161107_203215-768x786_w81qsf.jpg"],
          ["Combine the fish steaks with the fish sauce, thick soy sauce, garlic salt, black pepper, minced garlic and chopped shallots.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842075/20161107_202940-768x767_wgbjda.jpg"],
          ["Drain and rinse the mushrooms. Then add the mushrooms in with the fish steaks and marinade.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842083/20161107_202537-768x737_gnt0je.jpg"],
          ["Marinate for 15 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842105/20161107_202110-768x678_aelvac.jpg"],
          ["Pour in a tablespoon of cooking oil into a deep saute pan and turn the heat on to Medium High.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842110/20161107_201710-768x576_mgunqx.jpg"],
          ["Once the oil is hot add in the fish steaks only. Do not add the mushrooms or the marinade.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842118/20161107_201534-768x576_jm2wdj.jpg"],
          ["Cook the fish for about 2-3 minutes to lightly sear it. Then flip the fish over and again cook for 2-3 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842130/20161107_201352-768x578_kzukgp.jpg"],
          ["Now add in the mushrooms and the rest of the marinade that is in the bowl.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842142/20161107_201107-768x608_v8yrna.jpg"],
          ["Also add to the pan 3 tablespoons of fish sauce, 1 tablespoon of sugar , and 1/4 teaspoon of garlic salt. Boil on Medium High for 5 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842147/20161107_200947-768x632_vqc4sx.jpg"],
          ["Then pour in only half the can of coconut juice and reserve the rest for later.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842153/20161107_200808-768x781_ca5ydf.jpg"],
          ["Also toss in the Thai chili peppers. Bring to a boil and then reduce the heat to Medium Low. Simmer for 15 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842162/20161107_200436-768x679_avizz4.jpg"],
          ["Flip the fish over, pour in the rest of the coconut juice and simmer for another 15 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842169/20161107_195813-768x619_ugp3do.jpg"],
          ["Then turn off the heat. Wait about 10 minutes before serving to allow the fish to firm up a bit and the sauce to thicken up slightly.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842177/20161107_195127-768x641_dlpsib.jpg"],
          ["Sprinkle on some black pepper and garnish with chopped green onions.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842189/20161107_210457-1-768x723_xj9dwh.jpg"],
          ["Serve with white rice and a side of pickled beansprouts. (The recipe is available on my website as well.) If you do not want to serve the pickled beansprouts with the fish, then you can just serve it with some sliced Japanese cucumbers instead.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842270/20161107_205650-768x814_ze3q2m.jpg"],
        ],
    },
    {
        id: 13,
        name: "Carmelized Pork With Tofu - Thịt Kho",
        display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842759/20220519_220042-768x660_az0obr.jpg",
        videoId: "FsEilIdwE0E",
        summary: "Thịt Kho is a beloved Vietnamese dish made with tender pork shoulder slowly simmered in a rich caramelized sauce of coconut juice, fish sauce, and aromatics. This version includes soft tofu and your choice of eggs—either boiled or quail—for added texture and heartiness. Finished with a sprinkle of black pepper and green onions, it's a comforting and flavorful dish best enjoyed with steamed rice.",
        ingredients: [
            "For marinating the pork:",
            "1 tablespoon fish sauce",
            "1/2 tablespoon Maggi seasoning",
            "1 teaspoon garlic salt",
            "1/4 teaspoon black pepper",
            "1 teaspoon sugar",
            "1 tablespoon chicken seasoning",
            "For adding to the pan:",
            "2 tablespoons water",
            "2 tablespoons sugar",
            "2 1/2 lb pork shoulder butt, cut into smaller pieces",
            "5 garlic cloves, minced",
            "2 shallots (1/3 cup minced)",
            "1 can coconut juice (14 fl oz) — you may need 1 1/2 to 2 cans if you like a lot of sauce",
            "1 cup water",
            "1/4 cup fish sauce",
            "1 tablespoon Maggi seasoning",
            "1 tablespoon sugar",
            "Sprinkle of black pepper",
            "1 carrot, sliced, or 1 can quail eggs (your choice)",
            "7 boiled eggs (or 1 can of quail eggs — your choice)",
            "1/2 carton soft tofu (14 oz), cut into cubes",
            "For garnishing:",
            "Sprinkle of black pepper",
            "Handful of chopped green onions"
        ],          
        steps: [
          ["Boil eggs. Place the eggs in a small pot and fill with water. Bring to a boil then reduce the heat, cover and simmer for 12 minutes. Then drain and cover with cold water until cooled. Peel and set aside. If using canned quail eggs, you can skip this step and just drain the eggs. Give it a quick rinse and set them aside.", ""],
          ["Cut the pork into smaller chunks.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842643/20161019_142729-768x576_qnv8et.jpg"],
          ["Marinate with fish sauce, Maggi Seasoning, garlic salt, black pepper, sugar and chicken seasoning. Mix and marinate for at least 1 hour.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842647/20161019_143814-768x420_a27k9j.jpg"],
          ["Drain, rinse and cut the tofu into cubes. We only need to use half of the tofu. You can save the other half to use for another dish. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842654/20161019_152953-768x576_wmyxqz.jpg"],
          ["Mince the garlic and shallots. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842659/20161019_145407-768x576_bayiyh.jpg"],
          ["Wash and chop the green onions. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842664/20161019_154929-768x648_zanibh.jpg"],
          ["In a deep saute pan on Medium High heat add in 2 tablespoons of sugar and 2 tablespoons of water.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842670/20161019_1457260-768x576_kymv8e.jpg"],
          ["Allow the sugar to melt . Do not use a spoon to stir the sugar! The melted sugar will start to smoke as it starts to turn a brownish color.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842676/20161019_150800-768x576_tzzc3g.jpg"],
          ["At this point add in the meat and leave the pork undisturbed for a few minutes until browned .", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842685/20161019_151021-768x643_w2myuo.jpg"],
          ["Then toss in the minced garlic and shallots. Saute the meat for about 5 minutes until it has developed some color on both sides.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842690/20161019_151155-768x633_elacgd.jpg"],
          ["Then pour in the entire can of coconut juice and 1 cup of water.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842710/20161019_151431-768x694_kkoxvx.jpg"],
          ["Also add the fish sauce,", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842716/20161019_151257-768x696_jgfqlk.jpg"],
          ["Add the Maggi Seasoning.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842723/20161019_151710-768x685_peougn.jpg"],
          ["Add the sugar.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842730/20161019_151743-768x716_nxpufy.jpg"],
          ["And lastly add a sprinkle of black pepper. Stir and bring to a boil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842735/20161019_152015-768x498_aiul3e.jpg"],
          ["Once the sauce has come to a boil reduce the heat to Medium-Low. Cover and simmer for 40 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842740/20220519_220520-768x576_ddf6tu.jpg"],
          ["While the sauce is simmering be sure to skim off any foam from the top of the sauce.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842745/20161019_1530450-768x641_fzjyea.jpg"],
          ["After simmering the pork for 40 minutes, add in the sliced carrots. After adding the carrots bring the sauce back to a boil and then reduce the heat to Medium-Low. Cook the carrots for 20 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842753/20220519_220415-768x622_odlnkd.jpg"],
          ["Then add in the eggs ( either canned quail eggs or boiled chicken eggs ). Also add 1 cup to 1 and 1/4 cups of water if more sauce is needed or if it is too salty. Bring the sauce back to a boil and reduce the heat to Medium-Low. Cook for 5 minutes.", ""],
          ["Lastly, add in the tofu and cook for 5 minutes . Then sprinkle on some black pepper and garnish with a handful of chopped green onions.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842759/20220519_220042-768x660_az0obr.jpg"],
          ["Turn off the heat and leave it slightly uncovered on the stove for 30 minutes before serving.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842765/20161019_161432-768x576_qdmuqh.jpg"],
          ["Serve with white rice and pickled mustard greens or sliced japanese cucumbers.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1746842779/20201110_164708-768x576_cukawy.jpg"],
        ],
    },
    {
    id: 14,
    name: "Chicken Cabbage Salad (Gỏi Gà)",
    display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747011015/20170226_215449-768x861_yvxtxf.jpg",
    videoId: "yVhUnz9jJvc",
    summary: "This refreshing Vietnamese Chicken Cabbage Salad, known as Gỏi Gà, combines tender shredded chicken with crisp cabbage, sweet carrots, and fragrant herbs like mint, cilantro, and Vietnamese coriander. Light yet flavorful, this salad is typically served with a traditional fish sauce dressing, making it a perfect dish for warm weather or a light, satisfying meal.",
    ingredients: [
        "For boiling the chicken:",
        "2 chicken thighs, boiled and shredded",
        "Enough water to submerse the chicken thighs",
        "1 tablespoon salt",

        "For the salad:",
        "1/2 head of cabbage, shredded",
        "1 large carrot, shredded",
        "1 bunch Vietnamese coriander, roughly chopped",
        "1 bunch mint leaves, roughly chopped",
        "1 bunch cilantro, roughly chopped",

        "For making the pickled onions:",
        "1 medium onion, thinly sliced (red or yellow — your choice)",
        "1 cup unseasoned rice vinegar",
        "1 cup warm water",
        "1/3 cup sugar",
        "1/4 teaspoon salt",
        "1/8 teaspoon black pepper",

        "For topping with:",
        "Chopped roasted peanuts",
        "Fried red onions",

        "For serving with:",
        "Vietnamese fish sauce dipping sauce (recipe available on this website)"
    ],
    steps: [
      ["Thinly slice either a yellow onion or a red onion.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010949/20170226_084530-768x727_krlhg9.jpg"],
      ["In a bowl combine the rice vinegar, warm water, sugar, salt and black pepper.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010952/20170226_214336-768x684_spt7af.jpg"],
      ["Place the onion slices in the bow of vinegar mix. Soak for 45 minutes to an hour.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010957/20170226_214427-768x715_vbfweu.jpg"],
      ["Fill a pot with enough water to submerge the chicken thighs. Add a tablespoon of salt. Bring the pot of water to boil. Boil the chicken for 45 minutes or until cooked. Remove and let cool. Then hand shred the chicken thighs. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010963/20170226_214143-768x665_nrtayc.jpg"],
      ["Wash the Vietnamese coriander and rough chop.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010967/20170226_084050-768x645_gwqq9u.jpg"],
      ["Wash the mint leaves and rough chop.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010975/20170226_084130-768x576_xwutqj.jpg"],
      ["Wash the cilantro and rough chop.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010979/20170226_084238-768x695_wuvfqb.jpg"],
      ["Peel and shred the carrot.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010983/20170226_084356-1-768x693_dfrmh2.jpg"],
      ["Shred half a head of cabbage.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010987/20170226_084448-768x694_dfjrhs.jpg"],
      ["Place the shredded cabbage in a large mixing bowl.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010990/20170226_214725-768x713_uzf0gb.jpg"],
      ["Then add in the shredded carrots.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010994/20170226_214820-768x676_nrm2cs.jpg"],
      ["Add in 2-3 handfuls of the chopped Vietnamese coriander.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747010998/20170226_214915-768x710_qx3b4u.jpg"],
      ["Add in 2-3 handfuls of the chopped mint leaves and cilantro.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747011004/20170226_215026-768x726_beorap.jpg"],
      ["Add in the pickled onions (discard the brine). Add in as much or as little of the pickled onions as you'd like.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747011006/20170226_215150-768x659_ayqg4y.jpg"],
      ["Add in the cooked shredded chicken. Make sure the chicken is at least room temperature before mixing it into the salad. Then toss the salad well.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747011010/20170226_215330-768x714_dcmpxl.jpg"],
      ["Plate the salad. Top with a handful of chopped roasted peanuts and a handful of fried red onions.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747011015/20170226_215449-768x861_yvxtxf.jpg"],
      ["Drizzle some Vietnamese Fish Sauce dipping sauce over the salad or serve the Fish Sauce dipping sauce on the side.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747011018/20170226_215815-768x544_izfijp.jpg"],
      ["The salad can be eaten alone or with some white rice. It can also be eaten with some Vietnamese porridge.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747011021/20161228_145917-768x707_wlkrjk.jpg"],
    ],
},
{
    id: 15,
    name: "Chicken Curry – Cà Ri Gà",
    display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082964/tofu-final_gwkzm4.jpg",
    videoId: "zCys4SwLxkc",
    summary: "Cà Ri Gà is a rich and aromatic Vietnamese-style chicken curry made with tender leg quarters, hearty vegetables, and creamy coconut broth. Served with baguette or vermicelli noodles, this comforting dish is deeply flavorful and perfect for sharing.",
    ingredients: [
    "6 Chicken Leg Quarters (each cut into 3 sections)",
    "6 Ounces Fried Tofu (optional)",
    "For marinating the chicken",
    "1/4 Cup Fish Sauce",
    "1/2 Tablespoon Garlic Salt",
    "1/2 Teaspoon Black Pepper",
    "1 Tablespoon Sugar",
    "1 Tablespoon Totole Chicken Base Mix",
    "2 Tablespoons Curry Powder",
    "2 Tablespoons Grated Ginger (1 piece of ginger, ~3 inches)",
    "1 Tablespoon Minced Garlic",
    "3 Tablespoons Chopped Shallots",
    "For prepping",
    "3 Tablespoons Minced Garlic (1 tbsp for marinade, 2 tbsp for sauté)",
    "5 Tablespoons Chopped Shallots (3 tbsp for marinade, 2 tbsp for sauté)",
    "1 Large Yellow Onion (cut into wedges)",
    "2 Large Carrots (peeled and cut into bite-size pieces)",
    "3 Stalks Lemongrass (trim ends, bruise, cut into 2-inch sections)",
    "5 Russet Potatoes (peeled and cut into chunks)",
    "For placing with potatoes in a bowl",
    "9 Cups Water",
    "1 Tablespoon Salt",
    "For frying the potatoes (optional)",
    "4 Cups Vegetable Oil (for frying potatoes)",
    "For making the curry, adding to the pot",
    "24 Cups Water",
    "5 Cups Organic Chicken Broth",
    "2 1/2 Tablespoons Salt",
    "5 Bay Leaves",
    "1/2 Tablespoon Sugar",
    "1/3 Cup Fish Sauce",
    "2 Tablespoons Totole Chicken Base Mix",
    "1/2 Cup Curry Powder",
    "20 Ounces Coconut Cream",
    "For thickening the curry soup",
    "1 Cup Cold Water",
    "1 Cup Cornstarch",
    "For garnish (optional)",
    "Thai Basil",
    "Red Thai Chili Peppers",
    "Bean Sprouts (if serving with noodles)",
    "For lemon dip",
    "Lemon Wedges",
    "Pinch of Salt",
    "Pinch of Black Pepper",
    "For serving",
    "French Baguette (hot and fresh)",
    "OR Vermicelli Rice Stick Noodles"
    ],
    steps: [
      ["Mince the garlic (split the amount as noted in the preparation). Chop the shallots (split the amount as noted in the preparation). Grate the ginger. Then set aside.", ""],
      ["Wash the chicken and drain. If not already cut by the butcher, then cut each leg quarter into 3 sections.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747079679/20170419_140849-768x682_mre7wj.jpg"],
      ["Marinate the chicken with the fish sauce, garlic salt, black pepper, sugar, Totole chicken base mix and curry powder.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747079683/20170419_140801-768x629_g9sno9.jpg"],
      ["Toss the chicken to combine all of the ingredients.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747079688/20170419_140651-768x687_totyod.jpg"],
      ["Also add in 2 tablespoons of grated ginger, 1 tablespoon minced garlic, and 3 tablespoons of the chopped shallots. Marinate for at least 1 hour or more. Overnight is best.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747079692/20170418_130232-768x576_dmfavt.jpg"],
      ["Slice the onion into wedges . Cut the carrots into bite size pieces. Trim the ends of the lemongrass, then flatten the lemongrass with the back of a knife and cut the lemongrass into 2'' sections. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747081552/20170419_140430-768x687_rydcuq.jpg"],
      ["In a large bowl add in 9 cups of water and 1 tablespoon of salt. Peel the potatoes, cut into chunks and then add them to the salted water to prevent them from turning brown.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747081556/20170419_140515-768x603_ql1e0o.jpg"],
      ["Drain and dry the potatoes with some paper towels. Be sure they are dried well so that they do not splatter in the oil.", ""],
      ["Fry the potatoes in 2 to 3 batches. On Medium-High add 4 cups of vegetable oil to a wok.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747081566/20170419_140249-768x631_vhwg82.jpg"],
      ["Once the oil is hot carefully lower the potatoes into the oil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747081574/20170419_140205-768x572_de7x6p.jpg"],
      ["Fry the potatoes until browned. Remove the potatoes from the oil and place on a plate lined with paper towels to drain the excess oil. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747081578/20170419_140006-768x576_ef7vfh.jpg"],
      ["Saute the aromatics and cook the chicken. If your wok cannot fit all of the chicken pieces at one time then split the aromatics in half and saute the chicken in 2 batches if necessary. To begin, in a wok on medium-high heat, add 2 tablespoons of vegetable oil. Once the oil is hot, add 2 tablespoons of minced garlic, 2 tablespoons chopped shallots, 3 bay leaves, and the lemongrass. Even though the photo shows the onion wedges being added in at this time, please do not add them until later to prevent them from becoming too soft. Saute for about 1-2 minutes until fragrant.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747081582/20170418_142758-768x576_jlj7lj.jpg"],
      ["Then add in the chicken.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747081586/tofu-2_p6gpqo.jpg"],
      ["Cook the chicken for about 5-10 minutes or until the chicken is no longer pink on the outside. Then set the wok aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082534/20170418_143659-768x576_pwvkiw.jpg"],
      ["Make the curry. In an 16 quart stock pot on Medium-High add in 24 cups of water. Also add in 5 cups of chicken broth.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082539/20170419_125407-768x589_hsympr.jpg"],
      ["Add in 2 1/2 tablespoons of salt and 1/2 tablespoon of sugar.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082545/20170419_125318-768x537_pgs4yc.jpg"],
      ["Add in 1/3 cup of fish sauce.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082548/20170419_125224-768x562_rwpuv0.jpg"],
      ["Add in 2 tablespoons of Totole Chicken Base Mix.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082552/20170419_125133-768x595_n2jwts.jpg"],
      ["Add in 1/2 cup of curry powder. Stir and bring to a boil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082555/20170419_124657-768x610_kmmzax.jpg"],
      ["Then add in the chicken and bring back to a boil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082559/20170419_124551-768x604_bkzcnq.jpg"],
      ["Reduce the heat to Low, cover the pot with a lid and simmer for 5 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082562/20170419_085737-768x631_agkjbh.jpg"],
      ["During the entire cooking process skim off any foam or fat from the top of the curry. Discard the foam and fat.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082566/20170419_085948-768x656_hiu7cw.jpg"],
      ["After 5 minutes of simmering the curry, drop in the carrots, cover with a lid and bring the curry back to a boil. Then reduce heat and simmer the carrots for 10 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082570/20170419_085859-768x550_ilxwol.jpg"],
      ["Then drop in the fried potatoes and onion wedges.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082573/20170418_233409-768x448_of68b0.jpg"],
      ["Also pour in the entire can of coconut cream. Stir and bring to back to a boil. Then reduce the heat and simmer the curry for 10 minutes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082895/20170418_233236-768x498_hmpq8g.jpg"],
      ["Make the tapioca starch mixture to slightly thicken the curry. Pour 1 cup of cold water into a bowl then add in 1 cup of tapioca starch. Stir to dissolve tapioca starch. Reduce the heat to LOW then gradually pour in the tapioca starch mixture into the curry. Slowly stir the curry as you pour in the tapioca starch mixture. Cook the curry for another 5 minutes or until the chicken is cooked through and the carrots are tender.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082900/20170418_232218-768x581_gf7cac.jpg"],
      ["Now is the time to add in the fried tofu ( optional ).", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082905/tofu-1_ngxmno.jpg"],
      ["Once you have turned off the heat let the curry sit on the stove covered with a lid for about 15 - 30 minutes before you serve it ! It will allow for all the flavors to blend and the chicken to be really tender ! Also once it has cooled down a bit it will be easier to remove any leftover fat from the top of the curry.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082910/20170419_085737-768x631_hcqzor.jpg"],
      ["Garnish with some Thai Basils and sliced Thai Chili Peppers for extra heat (optional).", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082914/20170418_233700-768x576_dmcanj.jpg"],
      ["Enjoy!", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082920/20170419_195054-768x576_bvknbp.jpg"],
      ["The curry can be served with some french baguettes or rice. It can also be served over some Vermicelli Rice Stick Noodles with Thai basils and beansprouts.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082926/20170418_231457-768x726_yayobh.jpg"],
      ["(Optional) Lemon Juice Dip for the chicken. In a small dipping bowl add a pinch of salt and a pinch of black pepper. Then squeeze a wedge or two of lime into the bowl. Stir and dip your chicken pieces into the Lemon Juice dip!", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082931/20170418_233535-768x611_hmbpts.jpg"],
      ["Shown here and below are some of the brands used in this recipe as well as some extra notes.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082937/20170517_122828-e1495079204179-480x640_cqaotw.jpg"],
      ["Please note that deep frying the potatoes is optional.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082942/20170419_195156-595x919_b3l4yv.jpg"],
      ["And each time that you add a new ingredient to the pot of curry such as the carrots, potatoes, chicken, tapioca starch, etc, you will need to bring the curry back to a boil. Then reduce the heat to simmer.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082948/20170517_122704-e1495079393212-480x640_o8cwmi.jpg"],
      ["Also adding the fried tofu is optional.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082958/tofu-4_cusvef.jpg"],
      ["Enjoy the recipe!", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747082953/coconut-cream_ywo303.jpg"],
    ],
},
{
    id: 16,
    name: "Chicken Ragu",
    display: "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094527/20161024_190905-1-768x576_r4exme.jpg",
    videoId: "S4ESuZLGa_A",
    summary: "Chicken Ragu is a hearty and flavorful Vietnamese-inspired stew featuring tender chicken leg quarters simmered in a rich tomato-based sauce. The dish is infused with a savory blend of fish sauce, garlic, shallots, and aromatic herbs. Vegetables like carrots, potatoes, mushrooms, and tomatoes add depth and texture, while a touch of sugar balances the acidity of the tomato paste and Prego sauce.",
    ingredients: [
        "For adding to soup pot",
        "6 Chicken Leg Quarters (each cut into thirds)",
        "1/4 Cup + 4 Tablespoons Vegetable Oil (2 tbsp for sautéing tomatoes, 1/4 cup for chicken, 2 tbsp for onions)",
        "1/2 Stick of Butter",
        "1 Can Tomato Paste (6 oz)",
        "2 Containers Prego Sauce (1x 45 oz + 1x 24 oz, total 69 oz)",
        "1 Carton Chicken Broth (64 oz)",
        "1 Tablespoon Sugar",
        "1 1/2 Tablespoons Salt",
        "5 Bay Leaves",

        "For marinade",
        "1/3 Cup Fish Sauce",
        "1 Tablespoon Garlic Salt",
        "1 Teaspoon Black Pepper",
        "2 1/2 Tablespoons Chopped Garlic",
        "2 Tablespoons Chopped Shallots",

        "For vegatables",
        "4 1/2 Tablespoons Chopped Garlic (2 1/2 tbsp for marinade, 1 tbsp for sautéing chicken, 1 tbsp for tomatoes)",
        "5 Carrots (cut into bite-size pieces)",
        "5 Idaho Potatoes (cut into cubes)",
        "1 Carton Button Mushrooms (16 oz, sliced)",
        "8 Roma Tomatoes (cut into wedges)",
        "1 Large Onion (cut into wedges)",

        "For soaking potatoes",
        "Water (enough to cover potatoes)",
        "1 Tablespoon Salt",

        "For garnishing",
        "Black Pepper (to taste)",
        "Thai Basil",

        "For serving with",
        "French Bread"
    ],
    steps: [
      ["Wash and chop each leg quarter into thirds.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094345/20161024_204830-768x576_nyain2.jpg"],
      ["Marinate the chicken with fish sauce, garlic salt, black pepper, chopped garlic and shallots. Cover and refrigerate for a few hours. Before cooking the chicken be sure to bring the chicken back to room temperature.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094351/20161024_204717-768x603_f2d4lh.jpg"],
      ["Wash and cut the carrots, tomatoes and potatoes. Slice the mushrooms if they have not been pre-sliced. Cut the onion into wedges. Mince the garlic. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094356/20161024_194215-768x706_qbnapc.jpg"],
      ["Wash, peel and cut the potatoes into cubes. Fill a bowl with some water and add a tablespoon of salt. Place the cut potatoes into the bowl of salted water to keep them from turning brown. Leave the potatoes in the salted water until you are ready to add them to the soup. Before adding the potatoes to the soup be sure to give the potatoes a quick rinse. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094463/20161024_195318-768x576_fvglll.jpg"],
      ["Saute the tomatoes. In a saute pan on Medium High heat add 2 tablespoons of vegetable oil. Once the oil is warm add 1 tablespoon of garlic. Saute for 30 seconds. Then reduce the heat to Medium and add in the tomatoes. Saute for about 2-3 minutes. Add in 1 tablespoon of sugar and 1 teaspoon of salt. Cook the tomatoes until slightly softened. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094469/20161024_194044-768x665_qaamzk.jpg"],
      ["Cook the chicken. In a wok on Medium High add 1/4 cup of vegetable oil. Once the oil is warm add in 1 tablespoon of garlic and saute for 30 seconds. Then add in the chicken and let them sit in the pan for about 2-3 minutes undisturbed. Then saute the chicken until it is halfway cooked. Set aside.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094476/20161024_194612-768x576_x3zovg.jpg"],
      ["Make the sauce. In a large pot on High heat add 2 tablespoons of vegetable oil plus 1/2 stick of butter. Once the butter is melted reduce the heat to Medium then add in the tomato paste. Stir. Saute for another minute then add in the Prego Sauce and stir. Add in the Chicken Broth and stir. Add 1 tablespoon of sugar and 2 tablespoons of salt. Add the Bay leaves. Add in the tomatoes and stir. Bring the sauce to a boil.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094483/20161024_193943-768x660_oyvnaf.jpg"],
      ["Then add in the chicken. Discard the fat and juices at the bottom of the wok.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094490/20161024_140934-768x576_mhdbcs.jpg"],
      ["Also add in the carrots and potatoes. Bring the sauce back to a boil once more.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094496/20161024_193607-768x717_bvyehw.jpg"],
      ["Cover and simmer for 15 minutes. Stir occasionally.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094503/20161024_193454-768x623_j2a9kb.jpg"],
      ["Add the mushrooms and sliced onions . Bring the ragu back to a boil. Then cover and simmer for another 20 to 30 minutes until the chicken is cooked through and the vegetables are slightly softened. Stir occasionally.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094510/20161024_143046-768x576_a5clum.jpg"],
      ["Taste and adjust the soup. If you want it sweeter add more sugar. If it is too thick or salty add some water. If it needs more flavor you can add some chicken seasoning.", ""],
      ["Turn off the heat and leave the pot on the stove with the lid slightly uncovered for 30 minutes. This will allow the chicken to become tender.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094518/20161024_145353-768x576_asi1kj.jpg"],
      ["Ladle into a bowl. Sprinkle on some black pepper and garnish with Thai Basils.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094527/20161024_190905-1-768x576_r4exme.jpg"],
      ["Serve with french bread.", "https://res.cloudinary.com/dsqfvqtce/image/upload/v1747094535/Capture-bagueete_hqkdgu.png"],
      ["If the ragu ends up being too thick or salty, just add more water to it.", ""],
      ["You can use either the Prego Traditional sauce or the Prego Meat sauce  or a mix of both!  Typically this chicken ragu is made with only the Prego Traditional sauce but I prefer to mix one part of the Traditional sauce and one part of the Meat sauce.  And sometimes I will just use the Prego Meat sauce alone !", ""],
    ],
},
]

export default RecipeInfo;